default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: username
  password: password
development:
  <<: *default
  database: blog_dev

production:
  <<: *default
  database: blog_prod
